hands-on lab: Hit the RHODS
RedHatQuickCourses/rhods-qc-apps pull request #8
Opened 2023-11-08 15:44 UTC by jramcast

2023-11-09 10:07 UTC, mamurak commented
> The README file includes the lab instructions.
> 
> I had problems pulling the `quay.io/mmurakam/runtimes:fraud-detection-v0.2.0` runtime image for the pipeline (due to its large size I assume), so i decided to use the standard data science runtime image and then install `boto3` in the notebooks.
> 
>     * TODO: create runtime image for boto3 notebooks.

Interesting, can you describe the problem you're having with the runtime image? It would be important to fix this for running the pipeline @jramcast

2023-11-09 10:51 UTC, jramcast commented
@mamurak I get ImagePullBackOff errors in the pipeline pod, 1 or 2 minutes after running the pipeline. Just to double check, I did run `podman pull` locally with the same image and it works, so that's why I assumed that the cluster is hitting some kind of pull timeout or image size limit. 

FYI I tested in this in the [internal RHODS instance.](https://rhods-dashboard-redhat-ods-applications.apps.rhods-internal.61tk.p1.openshiftapps.com/). I still have to test this by using one of the demo catalog items.

2023-11-15 08:24 UTC, mamurak requested changes
Thanks for preparing this @jramcast. It looks great!
I've added a couple of minor comments. One thing we can look into is aligning this lab with the previous pipeline exercises; there's a lot that we can reuse here, see below.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> +In this exercise, you will create a complete data science project for detecting fraudulent credit card transactions.
```suggestion
In this exercise, you will complete the data science project for detecting fraudulent credit card transactions. In the previous exercise, you have seen how to run pipelines for detecting fraudulent transactions using a pre-trained model. Let's now create a new version of this model and deploy it!
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> +Your task is to complete the missing parts of those notebooks and create a data science pipeline to meet the lab specifications.
```suggestion
Your task is to complete the missing parts of those notebooks and create a data science pipeline and serve the model to meet the lab specifications.
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> +The lab scenario assumes that the dataset is available in the S3 bucket that you have created in the [RHODS administration quick course](https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1
We'll use the same bucket as in the [previous exercise](https://redhatquickcourses.github.io/rhods-pipelines/pr-preview/pr-3/rhods-pipelines/1.33/chapter1/section2.html#_data_science_pipeline_hands_on_example): `fraud-detection-bucket`

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> +* Perform your exercise in a TensorFlow workbench.
The recommendation is to avoid installing packages within workbench sessions. Students have already imported the fraud detection workbench, which includes the required dependencies, so we can reuse it here.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> +Make sure that the workbench size is at least `Medium`.
Small should be enough, no?

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> + Note that, in the [pipelines quick course](https://redhatquickcourses.github.io/rhods-pipelines/rhods-pipelines/1.33/index.html) you already created a pipeline for offline fraud detection, that is,
```suggestion
 Note that, in the [pipelines quick course](https://redhatquickcourses.github.io/rhods-pipelines/rhods-pipelines/1.33/index.html) you already created a pipeline for offline scoring, that is, for classification of unlabeled transactions given a pretrained model file.
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> +The model framework must be `onnx` version 1.
It should be self-evident after the exercises, so let's skip it.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/3.preprocessing.ipynb
> +    "save(f'data/training_samples.npy', Xsm_train)\n",
```suggestion
    "save('data/training_samples.npy', Xsm_train)\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/3.preprocessing.ipynb
> +    "save(f'data/training_labels.npy', ysm_train)\n",
```suggestion
    "save('data/training_labels.npy', ysm_train)\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/4.model_training.ipynb
> +    "Xsm_train = load(f'data/training_samples.npy')\n",
```suggestion
    "Xsm_train = load('data/training_samples.npy')\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/4.model_training.ipynb
> +    "ysm_train = load(f'data/training_labels.npy')\n",
```suggestion
    "ysm_train = load('data/training_labels.npy')\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/1.collect.ipynb
> +    "region = os.getenv(\"AWS_DEFAULT_REGION\")\n",
We can skip this.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/1.collect.ipynb
> +    "    region,\n",
We can skip this.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/1.collect.ipynb
> +    "S3_DATA_PATH = \"creditcard.csv\""
```suggestion
    "s3_data_path = \"creditcard.csv\""
```

We don't expect to treat this like an environment variable. Let's also move it into the next code block.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/1.collect.ipynb
> +    "%pip install boto3"
Remove once using custom workbench image.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/3.preprocessing.ipynb
> +    "%pip install imbalanced-learn==0.11.0"
Remove once using the custom workbench image.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/5.model_upload.ipynb
> +    "%pip install boto3"
Remove once using the custom workbench image.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/6.test.ipynb
> +    "INFERENCE_ENDPOINT = \"TODO\""
```suggestion
    "INFERENCE_ENDPOINT = \'TODO\'"
```

for consistency

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/1.collect.ipynb
> +    "%pip install boto3"
Remove once using the custom workbench image.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/3.preprocessing.ipynb
> +    "%pip install imbalanced-learn==0.11.0"
Remove once using the custom workbench image.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/3.preprocessing.ipynb
> +    "save(f'data/training_samples.npy', Xsm_train)\n",
```suggestion
    "save('data/training_samples.npy', Xsm_train)\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/3.preprocessing.ipynb
> +    "save(f'data/training_labels.npy', ysm_train)\n",
```suggestion
    "save('data/training_labels.npy', ysm_train)\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/4.model_training.ipynb
> +    "Xsm_train = load(f'data/training_samples.npy')\n",
```suggestion
    "Xsm_train = load('data/training_samples.npy')\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/4.model_training.ipynb
> +    "ysm_train = load(f'data/training_labels.npy')\n",
```suggestion
    "ysm_train = load('data/training_labels.npy')\n",
```

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/5.model_upload.ipynb
> +    "%pip install boto3"
Remove once using the custom workbench image.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/5.model_upload.ipynb
> +    "region = os.getenv(\"AWS_DEFAULT_REGION\")\n",
We can skip this.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/5.model_upload.ipynb
> +    "    region,\n",
We can skip this.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/mypipeline.pipeline
> +                "env_var": "AWS_DEFAULT_REGION",
We can skip this.

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/solutions/mypipeline.pipeline
In line with using a custom workbench image to avoid additional package installations in the IDE session, we can ask students to use this runtime image for the pipeline tasks, which includes the same libraries as the custom workbench:
quay.io/mmurakam/runtimes:fraud-detection-v0.1.0

2023-11-15 08:24 UTC, mamurak commented on 7.hands-on-lab/README.md
> + This pipeline must collect training data, preprocess the data, train the model, and upload the trained model.
Students can reuse the pipeline runtime image from the previous offline scoring pipeline. It contains the necessary dependencies:
quay.io/mmurakam/runtimes:fraud-detection-v0.1.0

2023-11-16 09:04 UTC, jramcast commented on 7.hands-on-lab/README.md
> +Make sure that the workbench size is at least `Medium`.
My kernel was running out of memory and crashing when using the `Small` size.

2023-11-16 09:15 UTC, mamurak commented on 7.hands-on-lab/README.md
> +Make sure that the workbench size is at least `Medium`.
If you're using the internal RHODS instance, the workbench sizes are different from the default ones. The default `Small` workbench has 8 GB RAM.

2023-11-16 09:22 UTC, jramcast commented on 7.hands-on-lab/solutions/1.collect.ipynb
> +    "    region,\n",
What do you mean by this? the region?

2023-11-16 09:26 UTC, mamurak commented on 7.hands-on-lab/solutions/1.collect.ipynb
> +    "    region,\n",
Yes, the region is not needed. It's an AWS-specific parameter that is optional and has no relevance in self-managed S3 like Minio.

2023-11-16 09:32 UTC, jramcast commented on 7.hands-on-lab/solutions/mypipeline.pipeline
[5a9741e](https://github.com/RedHatQuickCourses/rhods-qc-apps/pull/8/commits/5a9741e715116cc935d4f90dc998549adb37758e)

2023-11-16 09:35 UTC, jramcast commented
Thank you for your review @mamurak ! I have applied your suggestions.

Can you confirm that these are the right images to use?

* Workbench: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
* Runtime: quay.io/mmurakam/runtimes:fraud-detection-v0.1.0

Also,  just to double check, when using the `boto3` library, we should skip the region parameter, right?

2023-11-16 10:04 UTC, mamurak commented
> Thank you for your review @mamurak ! I have applied your suggestions.
> 
> Can you confirm that these are the right images to use?
> 
>     * Workbench: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
> 
>     * Runtime: quay.io/mmurakam/runtimes:fraud-detection-v0.1.0
> 
> 
> Also, just to double check, when using the `boto3` library, we should skip the region parameter, right?

Yes, the workbench and runtime images you referred to are correct.
Yes, I recommend to skip the region parameter since it's neither needed nor meaningful in our setting.

2023-11-16 10:39 UTC, jramcast commented
> > Thank you for your review @mamurak ! I have applied your suggestions.
> > Can you confirm that these are the right images to use?
> > ```
> > * Workbench: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
> > 
> > * Runtime: quay.io/mmurakam/runtimes:fraud-detection-v0.1.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, just to double check, when using the `boto3` library, we should skip the region parameter, right?
> 
> Yes, the workbench and runtime images you referred to are correct. Yes, I recommend to skip the region parameter since it's neither needed nor meaningful in our setting.

Awesome, thanks @mamurak . I have retested the whole exercise with those images, without the region parameter, and with the `Small` workbench size. It all works nicely!

One last detail I discovered: Even if the region parameter is not used in the notebooks nor the pipeline, it cannot be left blank. Otherwise, ModelServing fails indicating that it cannot browse the contents of the bucket because the region value is not set. In my case, setting the region value in the data connection to `default` worked.

2023-11-16 10:42 UTC, mamurak commented
> Thank you for your review @mamurak ! I have applied your suggestions.
> 
> Can you confirm that these are the right images to use?
> 
>     * Workbench: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
> 
>     * Runtime: quay.io/mmurakam/runtimes:fraud-detection-v0.1.0
> 
> 
> Also, just to double check, when using the `boto3` library, we should skip the region parameter, right?

Yes, the workbench and runtime images you referred to are correct.
Yes, I recommend to skip the region parameter since it's neither needed nor meaningful in our setting.

> > > Thank you for your review @mamurak ! I have applied your suggestions.
> > > Can you confirm that these are the right images to use?
> > > ```
> > > * Workbench: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
> > > 
> > > * Runtime: quay.io/mmurakam/runtimes:fraud-detection-v0.1.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, just to double check, when using the `boto3` library, we should skip the region parameter, right?
> > 
> > 
> > Yes, the workbench and runtime images you referred to are correct. Yes, I recommend to skip the region parameter since it's neither needed nor meaningful in our setting.
> 
> Awesome, thanks @mamurak . I have retested the whole exercise with those images, without the region parameter, and with the `Small` workbench size. It all works nicely!
> 
> One last detail I discovered: Even if the region parameter is not used in the notebooks nor the pipeline, it cannot be left blank. Otherwise, ModelServing fails indicating that it cannot browse the contents of the bucket because the region value is not set. In my case, setting the region value in the data connection to an arbitrary, non empty value, such as `default`, worked.

You're right, the RHODS dashboard requires the region parameter when defining a new data connection. It's best to leave the default value in case a specific region is not needed.

2023-11-16 12:06 UTC, mamurak approved these changes
Looks great, thank you for writing this up!

2023-11-16 13:53 UTC, merged